sysrepoctl -u o-ran-fan
sysrepoctl -u o-ran-fm
sysrepoctl -u o-ran-supervision
sysrepoctl -u o-ran-usermgmt
sysrepoctl -u o-ran-ves-subscribed-notifications
sysrepoctl -u o-ran-wg4-features
sysrepoctl -u o-ran-sync
sysrepoctl -u o-ran-ald
sysrepoctl -u o-ran-file-management
sysrepoctl -u o-ran-operations
sysrepoctl -u o-ran-software-management
sysrepoctl -u o-ran-trace
sysrepoctl -u o-ran-troubleshooting
sysrepoctl -u o-ran-ald-port
sysrepoctl -u o-ran-ethernet-forwarding
sysrepoctl -u o-ran-externalio
sysrepoctl -u o-ran-mplane-int
sysrepoctl -u o-ran-transceiver
sysrepoctl -u o-ran-antenna-calibration
sysrepoctl -u o-ran-beamforming
sysrepoctl -u o-ran-delay-management
sysrepoctl -u o-ran-laa
sysrepoctl -u o-ran-laa-operations
sysrepoctl -u o-ran-shared-cell
sysrepoctl -u o-ran-ecpri-delay
sysrepoctl -u o-ran-lbm
sysrepoctl -u o-ran-performance-management
sysrepoctl -u o-ran-udp-echo
sysrepoctl -u o-ran-uplane-conf
sysrepoctl -u o-ran-hardware
sysrepoctl -u o-ran-dhcp
sysrepoctl -u o-ran-processing-element
sysrepoctl -u o-ran-module-cap
sysrepoctl -u o-ran-compression-factors
sysrepoctl -u o-ran-interfaces
sysrepoctl -u iana-hardware
sysrepoctl -u iana-if-type
sysrepoctl -u ietf-crypto-types
sysrepoctl -u ietf-inet-types
sysrepoctl -u ietf-netconf-monitoring
sysrepoctl -u ietf-restconf
sysrepoctl -u ietf-yang-schema-mount
sysrepoctl -u ietf-yang-types
sysrepoctl -u ietf-yang-library
sysrepoctl -u ietf-network-instance
sysrepoctl -u ietf-subscribed-notifications
sysrepoctl -u ietf-ip
sysrepoctl -u ietf-interfaces
sysrepoctl -u ietf-netconf-acm
sysrepoctl -u ietf-dhcpv6-types
sysrepoctl -u ietf-datastores
sysrepoctl -u ietf-hardware
